#!/bin/sh

export TZ=Asia/Shanghai
export LC_ALL='en_US.UTF8'
export PATH=/home/admin/vdom/perl/bin/:$PATH

BIN=$(readlink -f -- $(dirname -- "$0"))
cd $BIN/..

export LD_LIBRARY_PATH=lib/:$LD_LIBRARY_PATH
sbin/nginx -s reload -c conf/nginx.conf


